services:
  # 1. SERVICE WEB DINAMIS
  uas_dinamis:
    image: irawatiiskandar/uas_dinamis:latest
    build: ./web-dinamis  # disesuaikan dengan folder 'web-dinamis' hasil ls Anda
    ports:
      - "3000:80"
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=perpustakaan_novel
      - DB_USER=root
      - DB_PASS=rootpassword
    volumes:
      - uploads_data:/var/www/html/uploads
    depends_on:
      - db

  # 2. SERVICE WEB STATIS
  uas_static:            # Sudah diganti pakai huruf 'c' di belakang
    image: irawatiiskandar/uas_static:latest
    build: ./web-statis   # disesuaikan dengan folder 'web-statis' hasil ls Anda
    ports:
      - "80:80"
    restart: always

# 3. SERVICE DATABASE
  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # <--- GANTI JADI PAKAI STRIP DAN SAMA DENGAN (=)
      - MYSQL_DATABASE=perpustakaan_novel # <--- GANTI JADI PAKAI STRIP DAN SAMA DENGAN (=)
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  db_data:
  uploads_data: