services:
  # 1. SERVICE WEB DINAMIS
  uas_dinamis:
    image: irawatiiskandar/uas_dinamis:latest
    build: ./uas_dinamis  # sesuaikan dengan nama folder project dinamis Anda
    ports:
      - "3000:80"
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=perpustakaan_novel
      - DB_USER=root
      - DB_PASS=rootpassword
    volumes:
      - uploads_data:/var/www/html/uploads
    depends_on:
      - db